site_name: "Compliance Trestle"
site_description: "Documentation for compliance-trestle package."
site_url: "https://compliance-trestle.github.io"
repo_url: "https://github.com/IBM/compliance-trestle"
repo_name: "IBM/compliance-trestle"

nav:
  - Overview: index.md
  - Trestle commands: commands.md
  - API Reference:
    - Overview: api_reference/overview.md
    - oscal:
      - Catalog: api_reference/oscal/catalog.md
      - Profile: api_reference/oscal/catalog.md
      - Component: api_reference/oscal/component.md
      - Target (Trestle defined): api_reference/oscal/target.md
      - System Security Plan: api_reference/oscal/ssp.md
      - System Assessment Plan: api_reference/oscal/sap.md
      - System Assessment Results: api_reference/oscal/sar.md
      - Plan of action & Milestones: api_reference/oscal/poam.md
    - core:
      - core: api_reference/core/core.md
      - models: api_reference/core/models.md
      - remote: api_reference/core/remote.md
  - API Reference 2: api_reference/all_in_one.md
  - Code of Conduct: mkdocs_code_of_conduct.md
  - Contributing:
      - Overview: contributing/mkdocs_contributing.md


theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple



markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            new_path_syntax: yes
            filters:
              - "!^_[^_]"
              - "!^__json"
              - "!^__config__"
          rendering:
            show_root_heading: True
            show_category_heading: True
            show_if_no_docstring: True
            group_by_category: True

      watch:
        - trestle