site_name: "Compliance Trestle"
site_description: "Documentation for compliance-trestle package."
site_url: "https://compliance-trestle.github.io"
repo_url: "https://github.com/IBM/compliance-trestle"
repo_name: "IBM/compliance-trestle"

nav:
  - Overview: index.md
  - Trestle commands: commands.md
  - Code of Conduct: mkdocs_code_of_conduct.md
  - Contributing:
      - Overview: contributing/mkdocs_contributing.md
  - Reference:
    - Overview: api_reference/overview.md
    - core:
      - base_model: api_reference/core/base_model.md
      - const: api_reference/core/const.md
      - duplicates_validator: api_reference/core/duplicates_validator.md
      - err: api_reference/core/err.md
      - generators: api_reference/core/generators.md
      - object_factory: api_reference/core/object_factory.md
      - parser: api_reference/core/parser.md
      - utils: api_reference/core/utils.md
      - validator_factory: api_reference/core/validator_factory.md
      - validator_helper: api_reference/core/validator_helper.md
      - commands: api_reference/core/commands/commands.md
      - models:
        - actions: api_reference/core/models/actions.md
        - elements: api_reference/core/models/elements.md
        - file_content_type: api_reference/core/models/file_content_type.md
        - interfaces: api_reference/core/models/interfaces.md
        - plans: api_reference/core/models/plans.md
    - oscal:
      - Catalog: api_reference/oscal/catalog.md
      - Profile: api_reference/oscal/catalog.md
      - Component: api_reference/oscal/component.md
      - Target (Trestle defined): api_reference/oscal/target.md
      - System Security Plan: api_reference/oscal/ssp.md
      - System Assessment Plan: api_reference/oscal/sap.md
      - System Assessment Results: api_reference/oscal/sar.md
      - Plan of action & Milestones: api_reference/oscal/poam.md
    - tasks:
      - base_task: api_reference/tasks/base_task.md
      - transform: api_reference/tasks/transform.md
    - utils:
      - fs: api_reference/utils/fs.md
      - log: api_reference/utils/log.md
      - trash: api_reference/utils/trash.md


theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple



markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            new_path_syntax: yes
            filters:
              - "!^_[^_]"
              - "!^__json"
              - "!^__config__"
          rendering:
            show_root_heading: True
            show_category_heading: True
            show_if_no_docstring: True
            group_by_category: True

      watch:
        - trestle